apiVersion: apps/v1
kind: Deployment
metadata:
  # Unique key of the Deployment instance
  name: deployment-nodedb-app
spec:
  # 3 Pods should exist at all times.
  replicas: 1
  selector:
    matchLabels:
      app: pod-nodedb-app
  template:
    metadata:
      labels:
        # Apply this label to pods and default
        # the Deployment label selector to this value
        app: pod-nodedb-app
    spec:
      containers:
      - name: container-nodedb-app
        # Run this image
        image: philippaul/node-mongo-db:02
      - name: mongo-db-container
        image: mongo